VIA_ENABLE = yes
VIAL_ENABLE = yes
LTO_ENABLE = yes
NKRO_ENABLE = no
MOUSEKEY_ENABLE = no
QMK_SETTINGS = no
VIAL_INSECURE = yes
OPT_DEFS += -DVIAL_VERY_INSECURE


# Extra options to save space
# TAP_DANCE_ENABLE = no
# COMBO_ENABLE = no
# KEY_OVERRIDE_ENABLE = no
